controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_L_joint"]  
    right_wheel_names: ["wheel_R_joint"]
    wheel_separation: 0.5  
    wheel_radius: 0.1      
    publish_rate: 50.0
    cmd_vel_topic: "cmd_vel_unstamped"
    use_stamped_vel: false